version: '3'
services:
  db:
    image: mysql:latest
    container_name: webauthn_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin21@Mysql
      - MYSQL_DATABASE=webauthn
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: